### ISSUE TITLE
Raspberry pi (armhf) docker image

### ISSUE THREAD

**Issue by SJ50** [XanderStrike/goplaxt#2]
I have RPI and it would be great if there is docker image for it.

**Comment by XanderStrike** [comment]
I like this idea a lot! Hopefully I'll have time this weekend to really dig into it.

**Comment by pabloromeo** [comment]
I managed to get it to build locally on an RPI, by changing iron/go for golang:latest (which supports ARM), both in the Dockerfile and in the build.sh.

I've never done any Go development, so i'm not sure if those two are 100% compatible, but Plaxt seems to run just fine. I've deployed it on a docker swarm and the webhooks and updates to Traktv seem to be working perfectly.

I assume the ideal solution would be to have the Plext image built as multi-arch and have it also support arm32v7 or a separate arm build and tag.

Also, a multi-stage docker build with the runtime based on alpine or scratch would also generate a much smaller output image of just a few MBs :). I didn't try that since i'm not familiar with Go and don't know if it has any runtime dependencies on the golang image.

**Comment by XanderStrike** [comment]
That's awesome! Thanks for doing that research. AFAIK Go binaries don't have any runtime dependencies (and plaxt has no external dependencies) so it should work fine even on a scratch image. If you'd like to open a PR I'll definitely merge it.

**Comment by pabloromeo** [comment]
Sure, I'll see if i can raise a PR later today or tomorrow, with a new multi-stage Dockerfile that can both build the code and package it inside a scratch image. That way you can probably integrate more easily into a CI pipeline/build. The new image based on scratch is only 6MB now, which is great news. I already have the Dockerfile, just need to make the changes in a fork and raise the PR.

Now regarding the ARM image, I don't know that much about multiarch images, manifests and how that actually works. I get the feeling that in order to get an ARM image you'd still need to also build it on a RPI or use QEMU (which i've never done).
But technically, I think the same Dockerfile in the PR should also be able to build an ARM image when building on ARM. I'm currently building and running it in RPI without a problem.

Maybe someone more knowledgeable than me on docker image architectures can pitch in on how we can build it for both in a simple manner.

**Comment by pabloromeo** [comment]
Also, from what I've read here (https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04) it seems like go can actually cross-compile to other architectures directly.
If that works maybe you can technically build both images yourself just by using different GOARCH arguments during the docker build process and the go build RUN command.

**Comment by pabloromeo** [comment]
BTW, I opened a PR for this ;)
https://github.com/XanderStrike/goplaxt/pull/23
