### ISSUE TITLE
Not working.. Returning 502 Bad Gateway

### ISSUE THREAD

**Issue by Guidoncio** [XanderStrike/goplaxt#44]
I noticed the webhook stopped working and tried to recreate. It´s returning 502 Bad Gateway when trying to authorize with Trakt.
![502-badgateway](https://user-images.githubusercontent.com/12549735/74492041-4f4cdc00-4eac-11ea-8858-a205c13f965f.png)

**Comment by XanderStrike** [comment]
Yeah this is happening a lot and I'm kind of at a loss as to why. It's always recovered by the time I see it.

**Comment by superxtc** [comment]
Happens to me as well.

**Comment by XanderStrike** [comment]
7 minutes later I checked and it seems to be working perfectly :(

Maybe try disabling adblockers or use an incogneto window? I don't even see a 502 being logged by the ingress proxy.

**Comment by superxtc** [comment]
It seems to be working now, thanks.
Unfortunately I don't know what the problem was, sorry.

**Comment by usernamenotavlbl** [comment]
it is down for anyone else?

**Comment by XanderStrike** [comment]
Interesting, it's getting pounded with for users with keys that are too old to be refreshed. I had been raising these as panics since they were supposed to be rare, but I think lots of people have >2 month gaps in their play history or de-authorized the integration in Trakt without removing the webhook. I'll try handling them and see if the error rate goes down.

**Comment by XanderStrike** [comment]
Alright, 502s look gone and it's deleting users who have invalid refresh tokens. I can't do anything about the endless ddos from those users, but at least now it's failing fast and not wasting cycles trying to refresh them.

**Comment by XanderStrike** [comment]
Monitoring has shown only a handful of 502s in the last 30 days so I'm gonna call this resolved 🎉
