### ISSUE TITLE
Scrobbling new Plex Movie Agent

### ISSUE THREAD

**Issue by geaston95** [XanderStrike/goplaxt#49]
Anyway to add support to scrobble the new Plex Movie Agent? Plaxt is currently unable to parse and track the new format

**Comment by XanderStrike** [comment]
This may be due to a bug I caught a couple months ago: https://forums.plex.tv/t/bug-webhooks-returning-multiple-guid-fields-of-different-datatypes/636921

The Plex team doesn't seem to care about bugs though.

I added a workaround to the library that parses webhooks, so maybe that will fix it. The images and public instance should be updated in a few hours and that should fix it I think.

**Comment by geaston95** [comment]
That seemed to have fixed it, thank you!
