### ISSUE TITLE
Webhook: Error delivering payload to http://plaxt.domain.com:8000/api?id=16c7ffa9262738e8d23657c33c37f603: 408

### ISSUE THREAD

**Issue by brimur** [XanderStrike/goplaxt#52]
Using the docker image. I set it up and was able to authorize successfully. When I start playing something in and watch the console I see the error...

````
Webhook: Error delivering payload to http://plaxt.domain.com:8000/api?id=16c7ffa9262738e8d23657c33c37f603: 408
````

I dont know what that means but if I paste the same URL into a browser I get this...

````
This page isn’t workingIf the problem continues, contact the site owner.
HTTP ERROR 405
````

Removing everthing after the port gives me the authorize page

**Comment by XanderStrike** [comment]
As far as I know there's no situation where Plaxt itself would return a 408 timeout, do you have an ingress proxy in the datapath that might have an aggressive timeout? Like an nginx reverse proxy or envoy or something.

What gets logged in Plaxt when that happens?

The 405 you got makes sense because `/api` only accepts post requests.

**Comment by XanderStrike** [comment]
Probably related to ingress not plaxt

**Comment by Paradoxum** [comment]
I am getting this on plex, just found it today, the webtools plugin of trakt doesn't seem to work anymore :|

Anyway, I authed with plaxt, entered my key, but my logs show:
Webhook: Error delivering payload to http://plaxt.astandke.com/api?id=ertr5e4545ddaa1d27edc9: 405
