### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Sc0tTyXL** [XanderStrike/goplaxt#57]
Hello,

It seems your hosted version is not working anymore.

Scrobbles are not showing up in my Trakt any more.

And when I tried creating new links the site doesnt work, jQuery is not loading:
![image](https://user-images.githubusercontent.com/24222938/123482064-f2ffdd80-d604-11eb-9752-36cb813e501b.png)

**Comment by ImjuzCY** [comment]
Yea, that's a bummer. Do you know of any alternatives?

**Comment by XanderStrike** [comment]
I just tested it and was able to generate a link that successfully scrobbles, I can also see from logs that it's continuing to work fine for lots of users. Doublecheck that javascript is enabled and you're not blocking the jQuery CDN and try again.

Trakt has [official plex webhooks support now](https://blog.trakt.tv/plex-scrobbler-52db9b016ead) so that's my recommended alternative.
