### ISSUE TITLE
Any plans to make this a 2-way sync?

### ISSUE THREAD

**Issue by DeviantEng** [XanderStrike/goplaxt#8]
Im super excited to see a webhook created for scrobbling to Plex, but are there plans for updating plex watched status FROM Trakt?  

I've relied on the TraktTV plugin for years to keep my watch status in sync, but that requires a 2-way sync.  Lately I've been having problems with the plugin, and found this when looking for alternatives.  But without a pull from Trakt function, this is a no go at this time.  Is this a planned feature?  Is it even possible to implement via webhook?

Thanks!

**Comment by XanderStrike** [comment]
No, it's not possible. Webohooks only send data, they cannot receive.

**Comment by pabloromeo** [comment]
There may be a way to push watch status changes from Traktv over to Plex, by making direct calls to Plex's api, maybe something like this:

`GET http://IP_OF_PMS:32400/:/scrobble?identifier=com.plexapp.plugins.library&key=54321&X-Plex-Token=XXXXXXXX`

Getting Plex metadata on the library (in order to match the "key" for each media) seems to be possible, since others seem to be doing it (such as https://github.com/phillipj/node-plex-api).
